apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
        - name: springbootapp
          image: sanjayadwani/springbootapp:v1.0
          imagePullPolicy: Always
          ports:
          - containerPort: 8084